// <auto-generated />
using System;
using KargoBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KargoBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220124057_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("KargoBackend.Entities.CargoRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedDeliveryRouteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetStationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDeliveryRouteId");

                    b.HasIndex("FromStationId");

                    b.HasIndex("TargetStationId");

                    b.HasIndex("UserId");

                    b.ToTable("CargoRequests");
                });

            modelBuilder.Entity("KargoBackend.Entities.DeliveryRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathGeometry")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanningRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RouteDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCargoCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalCost")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalDistanceKm")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalLoadKg")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanningRunId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DeliveryRoutes");
                });

            modelBuilder.Entity("KargoBackend.Entities.PlanningRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcceptedCargoCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostPerKm")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Objective")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlanDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("RentalVehicleCost")
                        .HasColumnType("REAL");

                    b.Property<int>("RentedVehicleCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalCost")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalLoadKg")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalRouteCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnassignedCargoCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlanningRuns");
                });

            modelBuilder.Entity("KargoBackend.Entities.RouteStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryRouteId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DistanceFromPreviousKm")
                        .HasColumnType("REAL");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StopOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryRouteId");

                    b.HasIndex("StationId");

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("KargoBackend.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KargoBackend.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDepot")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 904, DateTimeKind.Local).AddTicks(2250),
                            IsActive = true,
                            IsDepot = true,
                            Latitude = 40.821899999999999,
                            Longitude = 29.921099999999999,
                            Name = "Umuttepe Kampüsü (Merkez Depo)"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 908, DateTimeKind.Local).AddTicks(3920),
                            IsActive = true,
                            IsDepot = false,
                            Latitude = 40.7667,
                            Longitude = 29.916699999999999,
                            Name = "İzmit Merkez"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 908, DateTimeKind.Local).AddTicks(3930),
                            IsActive = true,
                            IsDepot = false,
                            Latitude = 40.802700000000002,
                            Longitude = 29.430700000000002,
                            Name = "Gebze"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 908, DateTimeKind.Local).AddTicks(3930),
                            IsActive = true,
                            IsDepot = false,
                            Latitude = 40.716799999999999,
                            Longitude = 29.817499999999999,
                            Name = "Gölcük"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 908, DateTimeKind.Local).AddTicks(3930),
                            IsActive = true,
                            IsDepot = false,
                            Latitude = 40.778100000000002,
                            Longitude = 29.7364,
                            Name = "Körfez"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 908, DateTimeKind.Local).AddTicks(3930),
                            IsActive = true,
                            IsDepot = false,
                            Latitude = 40.753399999999999,
                            Longitude = 30.023399999999999,
                            Name = "Kartepe"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 908, DateTimeKind.Local).AddTicks(3940),
                            IsActive = true,
                            IsDepot = false,
                            Latitude = 40.706699999999998,
                            Longitude = 29.932500000000001,
                            Name = "Başiskele"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 908, DateTimeKind.Local).AddTicks(3940),
                            IsActive = true,
                            IsDepot = false,
                            Latitude = 40.756399999999999,
                            Longitude = 29.8306,
                            Name = "Derince"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 908, DateTimeKind.Local).AddTicks(3940),
                            IsActive = true,
                            IsDepot = false,
                            Latitude = 40.690800000000003,
                            Longitude = 29.615300000000001,
                            Name = "Karamürsel"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 908, DateTimeKind.Local).AddTicks(3940),
                            IsActive = true,
                            IsDepot = false,
                            Latitude = 41.068300000000001,
                            Longitude = 30.149999999999999,
                            Name = "Kandıra"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 908, DateTimeKind.Local).AddTicks(3940),
                            IsActive = true,
                            IsDepot = false,
                            Latitude = 40.785299999999999,
                            Longitude = 29.5442,
                            Name = "Dilovası"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 20, 15, 40, 56, 908, DateTimeKind.Local).AddTicks(3940),
                            IsActive = true,
                            IsDepot = false,
                            Latitude = 40.8247,
                            Longitude = 29.3736,
                            Name = "Çayırova"
                        });
                });

            modelBuilder.Entity("KargoBackend.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CapacityKg")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("FixedRentalCost")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityKg = 500.0,
                            CreatedAt = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedRentalCost = 0.0,
                            IsActive = true,
                            PlateNumber = "41KRG01",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CapacityKg = 750.0,
                            CreatedAt = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedRentalCost = 0.0,
                            IsActive = true,
                            PlateNumber = "41KRG02",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            CapacityKg = 1000.0,
                            CreatedAt = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedRentalCost = 0.0,
                            IsActive = true,
                            PlateNumber = "41KRG03",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KargoBackend.Entities.CargoRequest", b =>
                {
                    b.HasOne("KargoBackend.Entities.DeliveryRoute", "AssignedDeliveryRoute")
                        .WithMany("CargoRequests")
                        .HasForeignKey("AssignedDeliveryRouteId");

                    b.HasOne("KargoBackend.Models.Station", "FromStation")
                        .WithMany()
                        .HasForeignKey("FromStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KargoBackend.Models.Station", "TargetStation")
                        .WithMany()
                        .HasForeignKey("TargetStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KargoBackend.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDeliveryRoute");

                    b.Navigation("FromStation");

                    b.Navigation("TargetStation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KargoBackend.Entities.DeliveryRoute", b =>
                {
                    b.HasOne("KargoBackend.Entities.PlanningRun", "PlanningRun")
                        .WithMany()
                        .HasForeignKey("PlanningRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KargoBackend.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanningRun");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("KargoBackend.Entities.RouteStop", b =>
                {
                    b.HasOne("KargoBackend.Entities.DeliveryRoute", null)
                        .WithMany("RouteStops")
                        .HasForeignKey("DeliveryRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KargoBackend.Models.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KargoBackend.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KargoBackend.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KargoBackend.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KargoBackend.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KargoBackend.Entities.DeliveryRoute", b =>
                {
                    b.Navigation("CargoRequests");

                    b.Navigation("RouteStops");
                });
#pragma warning restore 612, 618
        }
    }
}
